# Generated by Django 3.1.5 on 2021-03-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_auto_20210314_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='updated',
        ),
        migrations.AddField(
            model_name='slider',
            name='url_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
