# Generated by Django 3.1.5 on 2021-03-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailconfirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailconfirmed',
            name='hash_key',
        ),
        migrations.AddField(
            model_name='emailconfirmed',
            name='activation_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
