# Generated by Django 3.1.5 on 2021-03-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210301_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmed',
            name='activation_key',
            field=models.CharField(default='Empty', max_length=200),
            preserve_default=False,
        ),
    ]
