# Generated by Django 3.1.5 on 2021-02-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_variations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variations',
            new_name='Variation',
        ),
    ]
