# Generated by Django 3.1.7 on 2021-04-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210406_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='update_default',
            field=models.BooleanField(default=False),
        ),
    ]
